org: secondstate
app: tesseract
stage: prod

component: layer
name: tesseract-layer

inputs:
  region: ${env:region}
  src:
    bucket: ${output:${stage}:${app}:tesseract-cos.bucket}
    object: layer.zip
  runtimes:
    - CustomRuntime
